# Generated by Django 5.2.12 on 2026-04-07 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='score',
            new_name='rating',
        ),
        migrations.AddField(
            model_name='rating',
            name='timestamp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
