# Generated by Django 5.2.12 on 2026-04-21 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_poster_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='vote_average',
            field=models.FloatField(default=0.0),
        ),
    ]
